gästlista = ["Alex", "Emil", "Knark-Jonte", "Klas", "Kumla-Ljungan"]
message = "Kom och käka grillat och drick becherovka på uteplatsen."
print(f"Hej {gästlista[0]}! \n{message}")
print(f"Hej {gästlista[1]}! \n{message}")
print(f"Hej {gästlista[2]}! \n{message}")
print(f"Hej {gästlista[3]}! \n{message}")
print(f"Hej {gästlista[4]}! \n{message}")
print(f"skit också {gästlista[1]} kunde inte komma.")
gästlista.remove("Emil")
print(f"Hej {gästlista[0]}! \n{message}")
print(f"Hej {gästlista[1]}! \n{message}")
print(f"Hej {gästlista[2]}! \n{message}")
print(f"Hej {gästlista[3]}! \n{message}")
print("hittade större bord, bjuder in fler, brb")
gästlista.insert(0, "Emil")
gästlista.insert(3, "Nasse-Jonte")
gästlista.append("Tobbe")
print(gästlista)