ställen = ["Italien", "USA", "Grekland", "Frankrike", "Arktis"]
print(ställen)
print(sorted(ställen))
print(ställen)
print(sorted(ställen, reverse=True))
print(ställen)
print(sorted(ställen, reverse=False))
print(ställen)
ställen.sort()
print(ställen)
ställen.sort(reverse=True)
print(ställen)
ställen.sort(reverse=False)
print(ställen)
antalställen = len(ställen)
print(f"Jag vill besöka {antalställen} ställen.")
